config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  get '/orders' => 'order#index'

  get '/order/new' => 'order#new'
  post '/order/new' => 'order#create'

  get '/vendors' => 'vendor#index'
  get '/vendor/:name' => 'vendor#show'
  get '/payment/new/:from/:to' => 'payment#new', as: :payment_new
  post '/payment/new/' => 'payment#create'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  extend ActionView::Helpers::NumberHelper    # Access number functions

  belongs_to :user
  belongs_to :vendor
  has_one :payment


  validates :name, presence:true
  validates :price, numericality: {greater_than: 0},
  format: { :with => /\A\d+(?:\.\d{0,2})?\z/ } # 2 decimal max
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :city, presence:true
  
  def self.main_page
  	main_page = []
  	self.all.each do |o|
		main_page.push([o.city, o.name, o.price, o.quantity, number_to_phone(o.user.phone), o.date ])
	end
	main_page
  end


end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name:'User'
  has_one :order

  validates :price, numericality: {greater_than: 0},
  format: { :with => /\A\d+(?:\.\d{0,2})?\z/ } # 2 decimal max
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :fee, numericality: {greater_than: 0},
  format: { :with => /\A\d+(?:\.\d{0,2})?\z/ } # 2 decimal max

end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :user
  belongs_to :vendor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments_from, :class_name => 'Payment', :foreign_key => 'from_id'
  has_many :payments_to, :class_name => 'Payment', :foreign_key => 'to_id'
  has_many :orders

  validates :email, uniqueness: true, presence: true
  validates :address_line_1, presence:true
  validates :city, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :zip, presence: true


  validates :phone, presence:true, numericality: true, length: {in: 10..15}


  def phone=(val)
    if (val.gsub(/\s+/, "")!="")
      write_attribute(:phone, val.gsub(/\D/, '')[0, 14].to_i)
    end
  end

end

app/models/vendor.rb
class Vendor < ApplicationRecord
	has_many :orders

	def self.all_stores
		stores = []
		self.all.each do |s|
			stores.push([s.name])
		end
		stores
	end


	def store_page
		store_page = []
		orders.each do |o|
			store_page.push([o.city, o.name, o.price, o.quantity, o.date])
		end
		store_page
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
  end
  

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
	before_action :authenticate_user!, only: [:new]

	  
	def new

	end

	def create 
		u = current_user
		v = Vendor.find_by(name: params["order"]["vendor_name"])
		if !v.present?
			v = Vendor.create(name: params["order"]["vendor_name"])
			Order.create!(
			  		user_id: u.id,
			  		vendor_id: v.id,
			  		name: params["order"]["product_name"],
			  		price: params["order"]["price"],
			  		shipping: params["order"]["shipping"],
			  		quantity: params["order"]["quantity"],
			  		date: Time.now,
			  		city: params["order"]["city"])
			redirect_to orders_url
		else
			Order.create!(
			  		user_id: u.id,
			  		vendor_id: v.id,
			  		name: params["order"]["product_name"],
			  		price: params["order"]["price"],
			  		shipping: params["order"]["shipping"],
			  		quantity: params["order"]["quantity"],
			  		date: Time.now,
			  		city: params["order"]["city"])
			redirect_to orders_url
		end

	end

	def index
		@orders = Order.main_page

		respond_to do |format|
	      format.html
	      format.json {render json: @orders }
	    end
	end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
	before_action :authenticate_user!


	def new
	end

	def create
		Payment.create(
			from_id: params[:from],
			to_id: params[:to],
			price: params[:price])

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	

	
end

app/controllers/vendor_controller.rb
class VendorController < ApplicationController

	def index
		@vendors = Vendor.all_stores

		respond_to do |format|
	      format.html
	      format.json {render json: @vendors }
	    end
	end

	def show
		vendor = Vendor.find_by(name: params[:name])
		if vendor.present?
			@vendor = vendor
			respond_to do |format|
		      format.html
		      format.json {render json: @vendor.store_page }
		    end
		else
			@vendor = Vendor.create(name: params[:name])
			respond_to do |format|
		      format.html
		      format.json {render json: @vendor.store_page }
		    end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/views/home/index.html.erb
<div class="landing">
<div class="container-fluid">
	  <div class="row">
	    <div class="jumbotron">
	      <div class="col-fluid">
	        <h1>Introducing ShareShip</h1>
	        <h3>Save better together</h3>
	        <a href="order/new" class="btn" data-wipe="Get Started">Get Started</a>
	        <img class="truck" src="/assets/truck.png" alt="FedEx truck" height="350px" width="auto">
	      </div>
	    </div>
	  </div>
	</div>
	<div class="container-fluid">
	  <div class="row info">
	    <div class="col">
				<div class="idc">
	      <h1>Who are we?</h1>
	      <p>
	        Shareship is a company that provides our customers with the lowest possible shipping rate.
	        We do this through collective ordering, a process by which two neighbouring people who are ordering from the same retailer
	        order together to lower the overall cost of the shipment.
	      </p>
			</div>
	    </div>
	  </div>
	</div>
	<div class="container-fluid">
	  <div class="row info how">
	      <div class="col-md-12"><h1>How it works:</h1></div>
	      <div class="col-md-4">
	        <div class="story">
	          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
	          <p>
	            Buy something from your favourite retailer
	          </p>
	        </div>
	      </div>
	      <div class="col-md-4">
	        <div class="story">
	          <i class="fa fa-users" aria-hidden="true"></i>
	          <p>
	            Connect with someone else shopping from the same store
	          </p>
	        </div>
	      </div>
	      <div class="col-md-4">
	        <div class="story">
	          <i class="fa fa-money" aria-hidden="true"></i>
	          <p>
	            Save on delivery costs by shipping your item(s) together
	          </p>
	        </div>
	      </div>
	    </div>
	    </div>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shareship</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/header' %>
    <%= yield %>
  	<%= render 'shared/footer' %>
  </body>
</html>

app/views/order/index.html.erb
<div class="container">
  <div class="card">
    <div class="row">
      <div class="col-sm-12">
        <h1>Orders</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <table id="order-table" class="hover table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Shipping</th>
                <th>Quantity</th>
                <th>Phone Number</th>
                <th>Date</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% Order.all.each do |o| %>
                <tr>
                  <td><%= o.name %></td>
                  <td><%= o.price %></td>
                  <td><%= o.shipping %></td>
                  <td><%= o.quantity %></td>
                  <td><%= number_to_phone(o.user.phone) %></td>
                  <td><%= o.date.strftime("%m/%d/%Y") %></td>
                  <td><%= link_to 'Purchase', payment_new_url(current_user.id, o.user.id) %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- [o.city, o.name, o.price, o.quantity, number_to_phone(o.user.phone), o.date  -->

app/views/order/new.html.erb
<div class="logo">
  <i class="fa fa-truck" aria-hidden="true"></i>
</div>
<div class="container">
  <h1 class="form-signin-heading">New Order</h1>

  <%= form_for :order, html: {class: "form-signin form-signin2", id: "order"} do |f| %>
  <%= f.text_field :vendor_name, placeholder: "Vendor Name", class: "form-control yatin" %><br />
	<%= f.text_field :product_name, placeholder: "Product Name", class: "form-control yatin" %><br />
	<%= f.number_field :quantity, placeholder: "Quantity", class: "form-control yatin" %><br />
	<%= f.number_field :price, placeholder: "Price", class: "form-control yatin" %><br />
	<%= f.number_field :shipping, placeholder: "Shipping Cost", class: "form-control yatin" %><br />
	<%= f.text_field :city, placeholder: "City", class: "form-control yatin" %><br />
  <div class="col-sm-12">
			<button type="submit" form="order" class="btn btn-success" style="background-color:#2f80ed; border:#2f80ed" id="pay-now">Submit</button>
	</div>
  <% end %>
</div>

app/views/payment/new.html.erb
<div class="logo">
	<i class="fa fa-truck" aria-hidden="true"></i>
</div>
<h1 class="form-signin-heading">Payment</h1>
<body>
	<div class="container" style="margin-top: 50px;">
		<div class="row">
			<div class="offset-md-3 col-md-6">
				<form class="form-horizontal form-signin" role="form" action="/payment/new" id="pay-form" method="POST">
					<fieldset>
						<div class="form-group">
							<div class="col-sm-12">
								<input type="number" class="form-control" name="quantity" id="quantity" placeholder="Quantity Ordered">
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-12">
								<input type="number" step="0.01" class="form-control" name="price" id="price" placeholder="Product Price">
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-12">
								<input type="number" step="0.01" class="form-control" name="fee" id="fee" placeholder="Fee">
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-12">
								<input type="text" class="form-control" name="card-number" id="card-number" placeholder="Debit/Credit Card Number">
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-12">
									<div class="col-xs-6">
										<select class="form-control" name="expiry-month" id="expiry-month">
											<option>Month</option>
											<option value="01">Jan (01)</option>
											<option value="02">Feb (02)</option>
											<option value="03">Mar (03)</option>
											<option value="04">Apr (04)</option>
											<option value="05">May (05)</option>
											<option value="06">June (06)</option>
											<option value="07">July (07)</option>
											<option value="08">Aug (08)</option>
											<option value="09">Sep (09)</option>
											<option value="10">Oct (10)</option>
											<option value="11">Nov (11)</option>
											<option value="12">Dec (12)</option>
										</select>
									</div>
									<div class="col-xs-6">
										<select class="form-control" name="expiry-year">
											<option value="17">2017</option>
											<option value="18">2018</option>
											<option value="19">2019</option>
											<option value="20">2020</option>
											<option value="21">2021</option>
											<option value="22">2022</option>
											<option value="23">2023</option>
										</select>
									</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-12">
								<input type="text" class="form-control" name="cvv" id="cvv" placeholder="Security Code">
							</div>
						</div>
						<br>
						<div class="form-group">
							<div class="col-sm-12">
								<button type="submit" form="pay-form" class="btn btn-success" style="background-color:#2f80ed; border:#2f80ed" id="pay-now">Pay Now</button>
							</div>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>

</body>

app/views/shared/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<div class="col-sm-12">Footer</div>

app/views/shared/_header.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/">
      <i class="fa fa-truck" aria-hidden="true"></i>
      Home
    </a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/order/new">Create Order</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/orders">Find Listing</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to("Log Out", destroy_user_session_url, method: :delete, class: 'nav-link') %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Log In", new_user_session_url, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Sign Up", new_user_registration_url, class: 'nav-link' %></li>
      <% end %>
    </ul>
    <form id="search-form" onsubmit="redirectToVendor()">
      <input style="width: 30vw; padding:1%; border-radius:4px; border:black;" list="vendors-list" id="search_vendor" type="text" placeholder=" Search for a Vendor">
      <input style="background-color:black; color:white; font-weight:100; width: 5vw; padding:1%; border-radius:4px; border:black;" type="submit" value="Search">
    </form>  </div>

  <datalist id="vendors-list">

  </datalist>

<script>
function redirectToVendor(){
   var list_of_vendors = document.getElementById("vendors-list").getElementsByTagName("option");
   for (var i = 0; i < list_of_vendors.length; i++){
     if (list_of_vendors[i].value === document.getElementById("search_vendor").value){
       document.getElementById("search-form").action = "/vendor/" + document.getElementById("search_vendor").value;
       return;
     }
   }
}
</script>

</nav>